#!/usr/bin/env bash

if grep -q "^ml singularity" ~/.bashrc ~/.bash_profile; then
  read -p "Do you want to switch to apptainer in ~/.bashrc? [y/N] " -n 1 -r
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    sed -i '/^ml singularity\//d' ~/.bashrc ~/.bash_profile
    sed -i '/^ml apptainer\//d' ~/.bashrc ~/.bash_profile
    echo >> ~/.bashrc
    echo "ml apptainer/1.2.5 2> /dev/null" >> ~/.bashrc
    echo "Switched to apptainer in bashrc"
  elif [[ $REPLY =~ ^[Nn]$ || -z $REPLY ]]; then
    echo "Not switching to apptainer in ~/.bashrc"
    echo "To switch to apptainer in bashrc, add the folowing to your ~/.bashrc:"
    echo "ml apptainer/1.2.5 2> /dev/null"
    echo "And remove any existing ml singularity/ lines from ~/.bashrc and ~/.bash_profile"
  else
    echo "Invalid input"
  fi
elif ! grep -q "^ml apptainer" ~/.bashrc ~/.bash_profile; then
  echo "ml apptainer/1.2.5 2> /dev/null" >> ~/.bashrc
  echo "Added apptainer to ~/.bashrc"
else
  echo "Apptainer is already configured in ~/.bashrc"
fi

if [[ $SHELL != "/bin/bash" ]]; then
  echo "Apptainer is only configured for bash shells"
  echo "To configure apptainer for other shells, add the following to your shell's configuration file:"
  echo "ml apptainer/1.2.5 2> /dev/null"
fi

ml -q singularity singularity-ce &>/dev/null && ml -singularity -singularity-ce
ml apptainer/1.2.5

set +u +e +o pipefail
sycloud_added=false
if ! apptainer remote list | grep -q '^SylabsCloud'; then
  echo "SylabsCloud remote not found, adding it now"
  apptainer remote add --no-login SylabsCloud cloud.sycloud.io
  sycloud_added=true
fi

if ! apptainer remote list | grep -E -q '^SylabsCloud\s+(\w|\.)+\s+YES'; then
  if [[ $sycloud_added == "false" ]]; then
    echo "SylabsCloud remote not activated, activating it now"
  fi
  apptainer remote use SylabsCloud
fi

echo "Apptainer has been configured to use the SylabsCloud remote"