#!/bin/bash

###############################################################################
#                                                                             #
#  Script to run on a local computer to start Glances on Minerva and connect  #
#  to it with a local browser                                                 #
#                                                                             #
#  Main author     : Brian Fulton-Howard                                      #
#  Original author : Samuel Fux                                               #
#  Contributions   : Wei Guo, Gene Fluder, Lili Gai                           #
#                  : Andreas Lugmayr, Mike Boss                               #
#  Date            : October 2021                                             #
#  Location        : Mount Sinai (originally ETH Zurich)                      #
#  Version         : 0.7.2                                                    #
#  Change history  :                                                          #
#                                                                             #
#  02.07.2023    Adapt script for Glances                                     #
#  17.11.2022    Create remote dir, include session name in lsf lognames      #
#  17.11.2022    Move remote files                                            #
#  07.11.2022    Allow long jobs                                              #
#  03.10.2022    Native client compatibility with Apple Silicon               #
#  29.09.2022    Further refinements from rstudio;                            #
#                allow differnt hostnames on different clients                #
#  07.09.2022    Refinements from rstudio integration                         #
#  07.09.2022    Allow resource specification,                                #
#                generalize for integration of rstudio,                       #
#                automatically use first project unless specified,            #
#                and colorize outputs                                         #
#  07.07.2022    Fix launching outside of home directory and                  #
#                more robust token grabbing                                   #
#  07.07.2022    Fix browser opening on Mac and support WSL                   #
#  04.07.2022    Locks have potential fix but are disabled for now            #
#  30.06.2022    Locks and free ports on remote, improved native              #
#                remote storage of reconnect info, improved messages          #
#  22.06.2022    Allow simultaneous sessions and specifying folder            #
#  22.06.2022    Automatic multiplexing and check for code-server             #
#  22.06.2022    Allow and validate longer walltimes                          #
#  16.06.2022    Adapt for minerva and add autorestart support                #
#  19.05.2022    JOBID is now saved to reconnect_info file                    #
#  28.10.2021    Initial version of the script based on Jupyter script        #
#                                                                             #
###############################################################################

###############################################################################
# Configuration options, initalising variables and setting default values     #
###############################################################################

# Version
S_VERSION="0.7.2"

# Script directory
# old GLANCES_SCRIPTDIR=$(pwd)
S_SCRIPTDIR=$HOME

# hostname of the cluster to connect to
if grep -q 'Host minerva[[:space:]]*$' $HOME/.ssh/config &> /dev/null; then
  S_HOSTNAME="minerva"
elif grep -q 'Host chimera[[:space:]]*$' $HOME/.ssh/config &> /dev/null; then
  S_HOSTNAME="chimera"
fi

# Runtime limit default         : 12:00 hour
S_RUN_TIME="12:00"

# Node to monitor
S_NODE="login"

# Job ID to monitor
S_JOBID="none"

# True/False to kill the job
S_KILL="false"

# order for initializing configuration options
# 1. Defaults values set inside this script
# 2. Command line options overwrite defaults
# 3. Config file options  overwrite command line options

###############################################################################
# Text coloring                                                               #
###############################################################################

echoinfo () {
  echo -e "\033[32m[INFO] $@\033[0m"
}

echoerror () {
  echo -e "\033[31m[ERROR] $@\033[0m"
}

echoalert () {
  echo -e "\033[34;5m[INFO] $@\033[0m"
}

echowarn () {
  echo -e "\033[34;5m[WARNING] $@\033[0m"
}

###############################################################################
# Usage instructions                                                          #
###############################################################################

function display_help {
cat <<-EOF
$0: Script to start a Glances server on Minerva from a local computer

Usage: $(basename "$0") [options]

Optional arguments:

  -N | --node       login node       Node name or IP to monitor. Cannot use with
                                      -J/--job
  -J | --job        none             Job name or ID to monitor. Cannot use with
                                      -N/--node
  -p | --port                        Remote port to use for the server. Will not
                                      downoad config if specified.
  -K | --kill                        Kill the job and exit.
  -W | --runtime    12               Run time limit for the server in hours
                                      and minutes H[H[H]]:MM
  -c | --config     ~/.glnc_config    Configuration file for specifying options
  -h | --help                        Display help for this script and quit
  -v | --version                     Display version of the script and exit
  -s | --server     minerva          SSH arguments for connecting to the server:
                                      Will default to "minerva", then "chimera".
                                      server name from .ssh/config, or e.g.
                                      user@minerva.hpc.mssm.edu

Examples:

  $(basename $0) -N lc04a30

  $(basename $0) --runtime 01:30

  $(basename $0) -c $HOME/.glances_config -N lc04a30

Format of configuration file:

S_NODE="login"            # Node name or IP to monitor
S_RUN_TIME="01:00"        # Run time limit for the server in hours and
                            #   minutes H[H[H]]:MM
S_HOSTNAME="minerva"      # SSH host or username@host for connection

You should have SSH ControlMaster enabled in your ~/.ssh/config file for this to
work fully on the cluster. The script will manually multiplex otherwise, but
this is not recommended.

See https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Multiplexing

EOF
exit 1
}

###############################################################################
# Parse configuration options                                                 #
###############################################################################

while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help)
    display_help
    ;;
    -v|--version)
    echo -e "glance_minerva version: $S_VERSION\n"
    exit
    ;;
    -N|--node)
    S_NODE=$2
    shift; shift
    ;;
    -J|--job)
    S_JOBID=$2
    if [[ ! $S_NODE == "login" ]]; then
      echoerror "Cannot specify both node and job"
      exit 1
    fi
    shift; shift
    ;;
    -K|--kill)
    S_KILL="true"
    shift
    ;;
    -s|--server)
    S_HOSTNAME=$2
    shift; shift
    ;;
    -p|--remote-port)
    S_REMOTE_PORT=$2
    shift; shift
    ;;
    -W|--runtime)
    S_RUN_TIME=$2
    shift; shift
    ;;
    -c|--config)
    S_CONFIG_FILE=$2
    shift; shift
    ;;
    *)
    echowarn "ignoring unknown option $1 \n"
    shift
    ;;
  esac
done

###############################################################################
# Check key configuration options                                             #
###############################################################################

# check if user has a configuration file and source it to initialize options
if [ -f "$S_CONFIG_FILE" ]; then
  echoinfo "Found configuration file $S_CONFIG_FILE"
  echoinfo "Initializing configuration from file ${S_CONFIG_FILE}:"
  cat "$S_CONFIG_FILE"
  source "$S_CONFIG_FILE"
fi


# Check hostname
get_hostinfo() {
    awk -v hrx="[Hh][Oo][Ss][Tt][[:space:]]+$1[[:space:]]*$" \
   '$0 ~ "[Hh]ost[[:space:]]" {a = 0} $0 ~ hrx {a = 1; next} a == 1 {print}' \
   $HOME/.ssh/config | sed -E 's/^[[:blank:]]*|[[:blank:]]*$//g'
}

if [ -z ${S_HOSTNAME+x} ]; then
  echoerror "Hostname is not set. Please specify with --server option.\n\n"
  display_help
elif [[ "$S_HOSTNAME" =~ "@" ]]; then
  echoinfo "Valid username and server $S_HOSTNAME selected\n\n"
elif ! [ -f $HOME/.ssh/config ]; then
  echoerror "Username not specified and .ssh/config does not exist.\n\n"
  display_help
elif ! [[ $(get_hostinfo $S_HOSTNAME | wc -l) -gt 0 ]]; then
  echoerror "Username not specified and host not in .ssh/config.\n\n"
  display_help
elif ! get_hostinfo $S_HOSTNAME | grep -iq HostName; then
  echoerror "Hostname not specified in .ssh/config.\n\n"
  display_help
elif ! get_hostinfo $S_HOSTNAME | grep -iq User; then
  echoerror "Hostname not specified in .ssh/config.\n\n"
  display_help
else
  echoinfo "Connecting with the following settings:\n"
  get_hostinfo $S_HOSTNAME | grep -iE "HostName|User"
  echo
fi

# Check if multiplexing is enabled, otherwise warn and compensate
if ! [ -f $HOME/.ssh/config ] || \
   ! grep -q "ControlPath" $HOME/.ssh/config &> /dev/null; then
  echoalert "You should enable ControlMaster in your .ssh/config.\n"
  echoalert "See https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Multiplexing\n"
  if ! [ -d $HOME/.ssh/cm_socket ]; then
    mkdir -p $HOME/.ssh/cm_socket
  fi
  S_MANUAL_MULTIPLEX=true
  ssh -M -S ~/.ssh/cm_socket/%r@%h:%p -o "ControlPersist=10m" $S_HOSTNAME echo -e "Logged in as \$USER\n"
  S_HOSTNAME="-S ~/.ssh/cm_socket/%r@%h:%p $S_HOSTNAME"
fi

if [[ $S_JOBID != "none" ]]; then
  # Check if jobid is numeric
  if [[ $S_JOBID =~ ^[0-9]+$ ]]; then
    S_JOBQUERY=$(ssh $S_HOSTNAME -T bjobs -o first_host -noheader $S_JOBID)
    jobnotfound="Job <$S_JOBID> is not found"
    if [[ $S_JOBQUERY == $jobnotfound ]]; then
      echoerror "Job $S_JOBID not found on $S_HOSTNAME\n"
      exit 1
    else
      S_NODE=$S_JOBQUERY
      echoinfo "Found job $S_JOBID on node $S_NODE\n"
    fi
  else
    # Assume jobid is a jobname
    S_JOBNAME=$S_JOBID
    echoinfo "Detected jobname \"$S_JOBID\", searching for jobid"
    S_JOBQUERY=$(ssh $S_HOSTNAME -T "bjobs -o 'id name first_host'")
    jobhits=$(echo "$S_JOBQUERY" | awk -v a="$S_JOBID" 'NR == 1 || $2 == a {print $1}')
    if [ $(echo "$jobhits" | wc -l) -eq 1 ]; then
      echoerror "No jobs called \"$S_JOBNAME\" found on $S_HOSTNAME\n"
      exit 1
    elif [ $(echo "$jobhits" | wc -l) -gt 2 ]; then
      echoerror "Multiple jobs found on $S_HOSTNAME\n"
      echoerror "$S_JOBQUERY\n"
      exit 1
    else
      S_JOBID=$(echo "$jobhits" | tail -n 1)
      S_NODE=$(echo "$S_JOBQUERY" | awk -v a="$S_JOBID" '$1 == a {print $3}')
      echoinfo "Found job $S_JOBID on node $S_NODE matching the name \"$S_JOBNAME\"\n"
    fi
  fi
fi

if [[ $S_NODE == "login" ]]; then
  S_NODE_FWD="localhost"
else
  S_NODE_FWD=$S_NODE
fi

if [[ $S_KILL == true ]]; then
  ssh -T $S_HOSTNAME ssh $S_NODE bash <<ENDSSH
    gprocs () {
      ps -o "pid,cmd" -u "\$USER" | \
        sed -r 's/^\s+//;s/ /\t/' | \
        awk 'BEGIN {FS="\t"} \$2 ~ /glances/ && \$2 !~ /awk/ {print \$1}'
    }
    procs=\$(gprocs)
    #check if procs is empty
    if [ -z "\$procs" ]; then
      echo "glances not running"
    else
      echo "killing glances"
      echo "\$procs" | xargs kill
    fi
ENDSSH
  exit 0
fi

###############################################################################
# Set up directories and files                                                #
###############################################################################

echoinfo "Getting username and shell"
S_USERINFO=$(ssh -T $S_HOSTNAME 'getent passwd $USER')
S_REMOTE_SHELL=$(grep -Eo '[^/]+$' <<< $S_USERINFO)
S_USERNAME=$(grep -Eo '^[^:]+' <<< $S_USERINFO)

GLANCES_WORKDIR="/hpc/users/$S_USERNAME/minerva_jobs/glances"
S_BASE_RECONNECT=".reconnect_info_glances$S_NODE"
S_FILE_RECONNECT="$GLANCES_WORKDIR/$S_BASE_RECONNECT"
S_FILE_JOB="$GLANCES_WORKDIR/.glances$S_NODE.sh"
S_FILE_IP="$GLANCES_WORKDIR/glancesip$S_NODE"

###############################################################################
# Check directories and files                                                 #
###############################################################################

echoinfo "Checking directories"

info_workdir=$(echoinfo "Creating working directory")
ssh -T $S_HOSTNAME bash <<ENDSSH
# check workdir
if [[ ! -d $GLANCES_WORKDIR ]]; then
  mkdir -p $GLANCES_WORKDIR
  echo $info_workdir
fi
ENDSSH

###############################################################################
# Check for leftover files                                                    #
###############################################################################

# check for reconnect_info in the current directory on the local computer

macos_open () {
    if [[ $(uname -m) == "x86_64" ]]; then
    plat=x64
  else
    plat=arm64
  fi
  native_app="$HOME/.minerva_glances_app/glances_minerva${S_NODE}_$1-darwin-$plat/glances_minerva${S_NODE}_$1.app"
  already_open=$(ps aux | grep -i $native_app | grep -v grep | wc -l)
  if [[ $already_open -gt 0 ]]; then
    echoinfo "Already open in native mode"
  elif [[ -d $native_app ]]; then
    echoinfo "Opening in native mode"
    open -n $native_app
  elif which nativefier &> /dev/null; then
    nativefier --quiet -n "glances_minerva${S_NODE}_$1" \
      --darwin-dark-mode-support --fast-quit --enable-es3-apis \
      http://localhost:$1 $HOME/.minerva_glances_app 2> /dev/null
    echoinfo "Opening in native mode"
    sleep 2
    open -n $native_app
  elif open -n -a 'Google Chrome' --args "--app=http://localhost:$1" 2> /dev/null ; then
    echoinfo "Opened in Chromeless Google Chrome"
  else
    echoinfo "Opening in default browser"
    open "http://localhost:$1"
  fi
}

echoinfo "Checking if reconnection is possible\n"
S_RCI=$S_SCRIPTDIR/$S_BASE_RECONNECT

# Check if port is specified in $S_REMOTE_PORT
if [ -z ${S_REMOTE_PORT+x} ]; then
  if [ -z ${S_MANUAL_MULTIPLEX+x} ]; then
    scp $S_HOSTNAME:$S_FILE_RECONNECT $S_SCRIPTDIR/ &> /dev/null
  fi
else
  echoinfo "Using port $S_REMOTE_PORT"
  cat <<EOF > $S_RCI
Restart file
Remote hostname   : $S_NODE
Remote port       : $S_REMOTE_PORT
EOF
fi

find_port() {
  PRT=$1
  while ( lsof -i :$PRT -P -n | grep LISTEN &> /dev/null); do
    PRT=$((PRT+1))
  done
  echo $PRT
}

if [ -f $S_RCI ]; then
  RC_PRT_REMOTE=$(sed -nE 's/^Remote port +: (.+)/\1/p' $S_RCI)
  RC_NODE_REMOTE=$(sed -nE 's/^Remote hostname +: (.+)/\1/p' $S_RCI)
  S_CHECKJOB_CURL="-s $RC_NODE_REMOTE:$RC_PRT_REMOTE"
  S_CHECKJOB="curl $S_CHECKJOB_CURL | grep -q glances.js && echo running || echo dead"
  RC_JOBSTATE=$(ssh -T $S_HOSTNAME $S_CHECKJOB)

  if [[ $RC_JOBSTATE == "running" ]]; then
    sed 1d $S_RCI
    RC_SSH="ssh $S_HOSTNAME -L $RC_PRT:$RC_NODE_REMOTE:$RC_PRT_REMOTE -fNT"
    if grep -q "Local port" $S_RCI; then 
      RC_PRT=$(sed -nE 's/^Local[a-zA-Z ]+: (.+)/\1/p' $S_RCI)
      RC_URL=$(sed -nE 's/^URL[a-zA-Z ]+: (.+)/\1/p' $S_RCI)
    else
      echoinfo "Determining free port on local computer"
      RC_PRT=$(find_port 61234)
      RC_URL="http://localhost:$RC_PRT"
      echo -e "Local port        : $RC_PRT"
      echo -e "SSH tunnel        : $RC_SSH"
      echo -e "URL               : http://localhost:$RC_PRT"
    fi

    echo
    echoinfo "Starting browser and connecting it to the server"
    echoinfo "Connecting to url $RC_URL"

    # start local browser if possible
    if [[ "$OSTYPE" == "linux-gnu" ]]; then
      lsof -i :$RC_PRT > /dev/null || $RC_SSH
      if which wlslview 2>1 > /dev/null; then
        wslview $S_URL # USING Windows Subsystem for Linux
      elif ! [ -z ${WSLENV+x} ]; then
        echoalert "Your are using Windows Subsystem for Linux, but wslu is not "
        echoalert "available.\n"
        echoalert "Install wslu for automatic browser opening.\n"
        echoinfo "Please open $RC_URL in your browser."
      else
        xdg-open $RC_URL
      fi
    elif [[ "$OSTYPE" == "darwin"* ]]; then
      lsof -i :$RC_PRT > /dev/null || $RC_SSH
      macos_open $RC_PRT
    elif [[ "$OSTYPE" == "msys" ]]; then # Git Bash on Windows 10
      lsof -i :$RC_PRT > /dev/null || $RC_SSH # Don't know if this works
      start $RC_URL
    else
      echowarn "Your OS does not allow starting browsers automatically."
      echoinfo "Please open $RC_URL in your browser."
      echoinfo "check if port $RC_PRT is forwarded first."
    fi
    exit 0
  else
    echowarn "Job expired; checking for left over files from previous sessions"
    echoinfo "Found local session file, deleting it ..."
    rm $S_RCI
  fi
else
  echoinfo "Checking for left over files from previous sessions"
fi

# check for log files from a previous session in the home directory of the cluster
info_sessionfile=$(echoinfo "Found old remote session file, deleting it ...")
info_ipfile=$(echoinfo "Found old IP file, deleting it ...")
info_jobfile=$(echoinfo "Found old job file, deleting it ...")

ssh -T $S_HOSTNAME bash <<ENDSSH
if [[ -f $S_FILE_RECONNECT ]]; then
  echo $info_sessionfile
  rm $S_FILE_RECONNECT
fi

if [[ -f $S_FILE_IP ]]; then
  echo $info_ipfile
  rm $S_FILE_IP
fi

if [[ -f $S_FILE_JOB ]]; then
  echo $info_jobfile
  rm $S_FILE_JOB
fi
ENDSSH

echoinfo "Checking for glances on Minerva\n"

if ! ssh -tt $S_HOSTNAME 'bash -lc "which glances"' &> /dev/null; then
  echoerror "glances must be available in bash on Minerva.\n"
  echoerror "We suggest running 'mamba install -c conda-forge glances bottle' on"
  echoerror "Minerva if you use Anaconda and Mamba."
  exit 1
fi

###############################################################################
# Check configuration options                                                 #
###############################################################################

echoinfo "Validating command line options\n"

# check if S_RUN_TIME is provided in HH:MM format
if [[ "$S_RUN_TIME" =~ ^([0-9]{1,3}):([0-9]{2})$ ]]; then
  S_HOURS=${BASH_REMATCH[1]}
  S_MIN=$(echo ${BASH_REMATCH[2]} | sed 's/^0\(.\)$/\1/')
  S_MIN_TOT=$(($S_MIN + 60 * $S_HOURS))
  if [[ ( $S_MIN_TOT -gt 8640 && $S_QUEUE != "long" ) ||
        $S_MIN_TOT -gt 20160 ]]; then
    echoerror "$S_RUN_TIME -> Runtime limit is too long. Please try again\n"
    display_help
  fi
  echoinfo "Run time limit set to $S_RUN_TIME"
else
  echoerror "$S_RUN_TIME -> Incorrect format. Please specify runtime limit in the format H:MM, HH:MM, or HHH:MM and try again\n"
  display_help
fi

# Helper function to convert time to seconds
convert_to_seconds() {
  local time=$1
  local seconds=0

  if [[ $time =~ ^([0-9]{1,3}):([0-5][0-9])$ ]]; then
    local hours=${BASH_REMATCH[1]}
    local minutes=${BASH_REMATCH[2]}

    seconds=$((hours * 3600 + minutes * 60))
  else
    echo "Invalid time format. Please use H:MM, HH:MM, or HHH:MM."
    exit 1
  fi

  echo "$seconds"
}

S_RUN_TIME_SEC=$(convert_to_seconds $S_RUN_TIME)

###############################################################################
# Start glances on the cluster                                                #
###############################################################################

ssh $S_HOSTNAME "cat > $S_FILE_JOB" <<<cat <<EOF
#!/usr/bin/env bash
sink_stdout="$GLANCES_WORKDIR/glances_$S_NODE.out"
sink_stderr="$GLANCES_WORKDIR/glances_$S_NODE.err"

{
  sleep $S_RUN_TIME_SEC
  echo "Time limit reached, killing glances" > \$sink_stdout
  kill \$\$
} &

export http_proxy=http://172.28.7.1:3128
export https_proxy=http://172.28.7.1:3128
export all_proxy=http://172.28.7.1:3128
export no_proxy=localhost,*.chimera.hpc.mssm.edu,172.28.0.0/16

S_IP_REMOTE="\$(hostname -i)"
echo "Remote IP:\$S_IP_REMOTE" >> $S_FILE_IP

# Lockfiles disabled for now
# lf=/tmp/glances-session/
# mkdir -p \$lf
# if ! find \$lf -type f ! -mtime +7 ! -iname "\$USER" -exec false {} + ; then
# 	owner=\$(stat -c "%U" \$lf)
# 	if [[ \$USER != \$owner ]]; then
#     echo "FAIL" > $S_FILE_IP
#     echo "HOSTNAME:\$HOSTNAME" >> $S_FILE_IP
#     echo "OWNER:\$owner" >> $S_FILE_IP
#     exit 1
#   fi
# else
#   touch \$lf/\$USER
# fi

local_used_ports=\$(netstat -4 -ltn | grep LISTEN | awk '{ print \$4 }' | awk -F":" '{ print \$2 }' )

for p in {61208..61308}; do
  if [[ \$local_used_ports != *\$p* ]]; then
    S_PORT_REMOTE=\$p
		break
	fi
done

echo "Remote Port:\$S_PORT_REMOTE" >> $S_FILE_IP

# Run glances for the specified amout of time
glances --port \$S_PORT_REMOTE -f "username:$S_USERNAME" \
  -w --disable-plugin sensors,smart,diskio > \$sink_stdout 2> \$sink_stderr
EOF


TRY=1
SUCCESS=0

while ( [ $TRY -lt 4 ] && [ $SUCCESS -eq 0 ] ); do
  # run the job on Minerva and save the ip of the compute node in the home directory of the user
  echo

  if [[ $S_NODE == "login" ]]; then
    echoinfo "Running glances on login node"
    ssh $S_HOSTNAME "bash -l $S_FILE_JOB" &
  else
    echoinfo "Running glances on compute node $S_NODE"
    ssh $S_HOSTNAME "ssh $S_NODE \"bash -l $S_FILE_JOB\"" &
  fi
  
  # wait until batch job has started, poll every second to check if IP file exists
  # once the file exists and is not empty the batch job has started
  echoinfo "Waiting for server to start\n"
  ssh -T $S_HOSTNAME bash <<ENDSSH
  slept=0
  while ! [ -e $S_FILE_IP -a -s $S_FILE_IP ] && [ \$slept -lt 30 ]; do
    sleep 1
    slept=\$((slept+1))
  done
  sleep 4
ENDSSH

  # get remote port from files stored on Minerva
  if ssh -T $S_HOSTNAME "test -e $S_FILE_IP"; then
    ipfile=$(ssh -T $S_HOSTNAME "cat $S_FILE_IP")
  else
    echoerror "Could not find IP file on $S_HOSTNAME"
    exit 1
  fi
  if ! echo "$ipfile" | grep -q FAIL; then
    echoinfo "Receiving ip and port from the server"
    S_REMOTE_PORT=$(echo "$ipfile" | grep -m1 'Remote Port' | cut -d ':' -f2)
    SUCCESS=1
  else
    hostname=$(echo "$ipfile" | grep -m1 'HOSTNAME' | cut -d ':' -f2)
    owner=$(echo "$ipfile" | grep -m1 'OWNER' | cut -d ':' -f2)
    if [ $TRY -eq 3 ]; then
      echoerror "$owner is running a session on $hostname, therefore execution is blocked..."
      echoerror "Please resubmit your job to get your job dispatched to another node. "
      echoerror "Change your arguments like -n -M -W slightly."
      exit 1
    else
      echoalert "Attempt $TRY failed due to $owner running a session on $hostname:"
      echoalert "Trying again"
      ssh -T $S_HOSTNAME "rm $S_FILE_IP"
    fi
  fi
  TRY=$(($TRY+1))
done

# check if the port is defined
if  [[ "$S_REMOTE_PORT" == "" ]]; then
echoerror "remote port is not defined. Terminating script."
exit 1
fi

# get a free port on local computer
echoinfo "Determining free port on local computer"

if ! [ -z ${S_NODE+x} ]; then
  S_LOCAL_PORT=$(find_port 61208)
else
  S_LOCAL_PORT=$(find_port 8910)
fi

S_FWDCMD="ssh $S_HOSTNAME -L $S_LOCAL_PORT:$S_NODE_FWD:$S_REMOTE_PORT -fNT"

# setup SSH tunnel from local computer to compute node via login node
echoinfo "Setting up SSH tunnel for connecting the browser to the server"

# SSH tunnel is started in the background, pause 3 seconds to make sure
# it is established before starting the browser

# print information about IP, ports and token
echoinfo "Server info:"
echo
echo -e "Remote hostname    : $S_NODE_FWD"
echo -e "Remote port        : $S_REMOTE_PORT"
echo -e "Local port         : $S_LOCAL_PORT"
echo -e "SSH tunnel command : $S_FWDCMD"
echo -e "URL                : http://localhost:$S_LOCAL_PORT"
echo

# write reconnect_info file
cat <<EOF > $S_RCI
Restart file
Remote hostname   : $S_NODE_FWD
Remote port       : $S_REMOTE_PORT
Local port        : $S_LOCAL_PORT
SSH tunnel        : $S_FWDCMD
URL               : http://localhost:$S_LOCAL_PORT
EOF

# Copy connection information to the remote machine
if [ -z ${S_MANUAL_MULTIPLEX+x} ]; then
  scp $S_RCI $S_HOSTNAME:$S_FILE_RECONNECT &> /dev/null
fi

# save url in variable
S_URL=http://localhost:$S_LOCAL_PORT
echoinfo "Starting browser and connecting it to the server"
echoinfo "Connecting to url $S_URL"

# start local browser if possible
if [[ "$OSTYPE" == "linux-gnu" ]]; then
  if which wlslview 2>1 > /dev/null; then
    wslview $S_URL # USING Windows Subsystem for Linux
  elif ! [ -z ${WSLENV+x} ]; then
    echowarn "Your are using Windows Subsystem for Linux, but wslu is not "
    echowarn "available.\n"
    echowarn "Install wslu for automatic browser opening.\n"
    echoinfo "Please open $S_URL in your browser."
  else
    xdg-open $S_URL
  fi
elif [[ "$OSTYPE" == "darwin"* ]]; then
  macos_open $S_LOCAL_PORT
elif [[ "$OSTYPE" == "msys" ]]; then # Git Bash on Windows 10
  start $S_URL
else
  echowarn "Your OS does not allow starting browsers automatically."
  echoinfo "Please open $S_URL in your browser."
fi
